name: All3DP Newsletter Templates - CICD

on:
  push:
    branches: ["released", "main"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install YARN
        run: npm install -g yarn@^1

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3

      - name: Package install
        run: |
          yarn install

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
