name: All3DP Newsletter Templates - CICD

on:
  push:
    branches: ["released", "main"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm install

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build
